name: geojson_vi
description: An Open-Source Dart and Flutter Library for Efficiently Handling GeoJSON Data in Compliance with RFC 7946

version: 2.2.0
homepage: https://github.com/chuyentt/geojson_vi

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
